# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0025_delete_emergency_exit_door'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('type', models.CharField(choices=[(b'electrical equipment', 'electrical equipment'), (b'emergency exit door', 'emergency exit door'), (b'emergency lamp', 'emergency lamp'), (b'entrance door', 'entrance door'), (b'downpipe', 'downpipe'), (b'fireproof door', 'fireproof door')], max_length=30, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='equipment_inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_condition', models.CharField(choices=[(b'normal', 'Normal'), (b'breakdown', 'Breakdown')], default=b'normal', max_length=30, verbose_name='Use Condition')),
                ('inspector', models.CharField(max_length=30, verbose_name='Inspector')),
                ('date_of_inspection', models.DateTimeField(auto_now=True, verbose_name='Date of Inspection')),
            ],
            options={
                'verbose_name': 'equipment inspection',
            },
        ),
    ]
