# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0026_equipment_equipment_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_inspection',
            name='equipment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inspection.equipment'),
            preserve_default=False,
        ),
    ]
