# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0027_equipment_inspection_equipment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='equipment_inspection',
            new_name='ElectricalEquipmentInspection',
        ),
        migrations.AlterModelOptions(
            name='electricalequipmentinspection',
            options={},
        ),
    ]
