# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 02:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0028_auto_20171008_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricalequipmentinspection',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 8, 2, 14, 46, 236000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electricalequipmentinspection',
            name='date_of_inspection',
            field=models.DateField(verbose_name='Date of Inspection'),
        ),
    ]
