# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0029_auto_20171008_1014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electricalequipmentinspection',
            unique_together=set([('equipment', 'inspector', 'date_of_inspection')]),
        ),
    ]
