# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0030_auto_20171008_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprayPumpRoomInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_and_power_normal', models.BooleanField(default=False, verbose_name='voltage and power normal')),
            ],
        ),
    ]
