# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0031_spraypumproominspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='spraypumproominspection',
            name='month',
            field=models.CharField(choices=[(b'jan', 'Jan'), (b'feb', 'Feb')], default=b'jan', max_length=30, verbose_name='Month'),
        ),
    ]
