# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0032_spraypumproominspection_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='spraypumproominspection',
            name='indicator_and_instrument_normal',
            field=models.BooleanField(default=False, verbose_name='indicator and instrument normal'),
        ),
    ]
