# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTraningPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(verbose_name='Date')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('location', models.CharField(max_length=30, verbose_name='Location')),
                ('topic', models.CharField(max_length=150, verbose_name='Topic')),
                ('type', models.CharField(max_length=150, verbose_name='type')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
        ),
        migrations.AddField(
            model_name='annualtraningplan',
            name='training_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingCourse'),
        ),
    ]
